### PR TITLE
Update to AzureStorageDsc

### PR DESCRIPTION
**Pull request by BrianFarnhill**
@kwirkykat are you able to do a review of this one against the HQRM rules so we can ditch the x off this module and ship it. It's only a small module so hopefully this will be a quick one :)

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xazurestorage/5)

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
The tests are failing because the AppVeyor project name is still xAzureStorage - the script for the exmaple test there relies on that value. You can see the latest test from my branch where I've renamed it on my end to verify that - https://ci.appveyor.com/project/BrianFarnhill/azurestoragedsc/build/1.0.0.4

**Comment by BrianFarnhill** [comment]
@kwirkykat Any chance we can get a review of this one?

**Review by kwirkykat — APPROVED** [review]

**Comment by kwirkykat** [comment]
@BrianFarnhill Doesn't look like this module is currently part of the DSC Resource Kit. I'm not sure who owns it but I have no merge/release permissions here. I will ask around

**Comment by kwirkykat** [comment]
@BrianFarnhill  Looks like you're really the only contributor here. Was this part of the DSC Resource Kit before? It's not under the [submodules of DscResources](https://github.com/PowerShell/DscResources/tree/master/xDscResources) but it looks like maybe that was a mistake?

**Comment by BrianFarnhill** [comment]
@kwirkykat Yea I own it, I remember submitting it to be part of the toolkit ages ago but you're right it never looks like it made it in. I'm sure I could dig out the email trail from back in the day before you took over around that, but never mind. Do you wanna treat this as a new module then and give it the full review treatment before we bring it in if that makes more sense?

**Comment by johlju** [comment]
@kwirkykat @BrianFarnhill Where should we go with this one? Since this repo is under the PowerShell Team organization, should we just add it to DscResources after this PR is through? We have similar scenario in issue https://github.com/PowerShell/DscResources/issues/36 where the resource module is under the PowerShell Team organization.

**Comment by BrianFarnhill** [comment]
@johlju Yea I think this was meant to have been in the DscResources list but got overlooked at some point and I never chased it up that.

**Comment by kwirkykat** [comment]
@johlju @BrianFarnhill  Yeah since this is already under PS org, it looks like it was just not added to the submodules of DscResources so it was overlooked in the Resource Kit. I think we can just discreetly add it back into the list. Since it wasn't added though, I don't have permissions to rename this repo or merge anything. @Indhukrishna Can you add this to the list of repos that the DscMaintainers team has access to under the PowerShell org?

**Pull request closed without merging**
